[package]
name = "opthash"
version = "0.1.1"
edition = "2024"
description = "Rust implementations of Elastic Hashing and Funnel Hashing"
readme = "README.md"
repository = "https://github.com/aaron-ang/opthash"
license = "MIT OR Apache-2.0"
keywords = ["hashmap", "open_addressing", "elastic_hashing", "funnel_hashing"]
categories = ["algorithms", "data-structures"]
exclude = ["benches/*", "paper/*"]

[dependencies]

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }

[[bench]]
name = "throughput"
harness = false
